test:
  bradesco:
    carteira: 09
    nome_empresa: FIDC TESTE
    convenio: 4359923
    conta_corrente: 0147792-2
    agencia: 00289

development:
  bradesco:
    carteira: 09
    nome_empresa: FIDC TESTE
    convenio: 4359923
    conta_corrente: 0147792-2
    agencia: 00289
